// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$ReasonSpotifyClient = require("./App.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(App$ReasonSpotifyClient.make, { }), "index");

/*  Not a pure module */
